import { Worker, Job as BullJob } from "bullmq";
import { prisma } from "../services/prisma.js";
import { GeminiService } from "../services/gemini.service.js";
import { redisConnectionOptions } from "./queue.js";

interface OutreachJobData {
  generationJobId: string;
}

const geminiService = new GeminiService();

export const outreachWorker = new Worker(
  "outreach-generation",
  async (bullJob: BullJob<OutreachJobData>) => {
    const { generationJobId } = bullJob.data;
    console.log(`[Outreach Worker] Starting message generation for Job ID: ${generationJobId}`);

    // 1. Fetch the GenerationJob details
    const genJob = await prisma.generationJob.findUnique({
      where: { id: generationJobId },
      include: {
        profile: true,
        resume: true,
        template: true,
      },
    });

    if (!genJob) {
      throw new Error(`GenerationJob with ID ${generationJobId} not found in database.`);
    }

    try {
      // 2. Set status to GENERATING
      await prisma.generationJob.update({
        where: { id: generationJobId },
        data: { status: "GENERATING" },
      });

      // 3. Load optional target Job details
      let jobDetails: { title: string; company: string; description?: string | null } | null = null;
      if (genJob.jobId) {
        const job = await prisma.job.findUnique({
          where: { id: genJob.jobId },
        });
        if (job) {
          jobDetails = {
            title: job.title,
            company: job.company,
            description: job.description,
          };
        }
      }

      // 4. Generate the personalized message using Gemini AI
      console.log(`[Outreach Worker] Requesting personalized message for ${genJob.profile.name} at ${genJob.profile.company}...`);
      const generated = await geminiService.generateOutreachMessage(
        {
          name: genJob.profile.name,
          role: genJob.profile.role,
          company: genJob.profile.company,
          notes: genJob.profile.notes,
        },
        {
          parsedText: genJob.resume.parsedText,
          skills: genJob.resume.skills,
          experience: genJob.resume.experience,
          projects: genJob.resume.projects,
        },
        jobDetails,
        genJob.template.prompt,
        genJob.template.type
      );

      console.log(`[Outreach Worker] Message successfully generated by Gemini AI.`);

      // 5. Update the GenerationJob state to COMPLETED
      await prisma.generationJob.update({
        where: { id: generationJobId },
        data: {
          status: "COMPLETED",
          generatedSubject: generated.subject,
          generatedMessage: generated.body,
        },
      });

      // 6. Create a draft in the OutboundMessage queue for the user's manual Approval Workflow!
      await prisma.outboundMessage.create({
        data: {
          profileId: genJob.profileId,
          channel: "EMAIL",
          subject: generated.subject,
          content: generated.body,
          status: "DRAFT", // Messages enter DRAFT mode waiting for manual user approval
        },
      });

      console.log(`[Outreach Worker] Enqueued DRAFT message in the manual approval queue.`);

    } catch (error) {
      const errMsg = error instanceof Error ? error.message : String(error);
      console.error(`[Outreach Worker] CRITICAL FAILURE for Generation Job ID ${generationJobId}:`, error);

      // Update GenerationJob status to FAILED and store the error logs
      await prisma.generationJob.update({
        where: { id: generationJobId },
        data: {
          status: "FAILED",
          error: errMsg,
        },
      });

      throw error; // Re-throw to let BullMQ mark it as failed in Redis
    }
  },
  {
    connection: redisConnectionOptions,
    concurrency: 2, // Concurrency 2 is safe for Gemini flash models
  }
);

outreachWorker.on("completed", (job) => {
  console.log(`[Outreach Worker] Job ${job?.id} completed successfully.`);
});

outreachWorker.on("failed", (job, err) => {
  console.error(`[Outreach Worker] Job ${job?.id} failed:`, err);
});
